// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Service.Infra.Data.Context;

#nullable disable

namespace Service.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260924195641_AddAllModulePermissions")]
    partial class AddAllModulePermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Service.Domain.Entities.AllocationGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AllocationGroups", (string)null);
                });

            modelBuilder.Entity("Service.Domain.Entities.BufferAdjustmentFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AlreadyReverted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("BufferDdmrpGreen")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("BufferDdmrpGreenOld")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("BufferDdmrpRed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("BufferDdmrpRedBaseOld")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("BufferDdmrpRedSafeOld")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("BufferDdmrpYellow")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("BufferDdmrpYellowOld")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("BufferType")
                        .HasColumnType("int");

                    b.Property<int?>("BufferTypeOld")
                        .HasColumnType("int");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCenter")
                        .HasColumnType("int");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Obs")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCenter");

                    b.HasIndex("IdProduct");

                    b.ToTable("BufferAdjustmentFactors", (string)null);
                });

            modelBuilder.Entity("Service.Domain.Entities.BufferProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AduCalculationDays")
                        .HasColumnType("int");

                    b.Property<int>("AduFutureDays")
                        .HasColumnType("int");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<bool>("GreenZoneParametrizationUseAduXFrequency")
                        .HasColumnType("bit");

                    b.Property<bool>("GreenZoneParametrizationUseAduXLeadTimeXFactLeadTime")
                        .HasColumnType("bit");

                    b.Property<bool>("GreenZoneParametrizationUseMoq")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMakeToOrder")
                        .HasColumnType("bit");

                    b.Property<int>("LeadTimeCategory")
                        .HasColumnType("int");

                    b.Property<decimal>("LeadTimeFactor")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("SpikeHorizonLTDays")
                        .HasColumnType("int");

                    b.Property<int>("SpikeHorizonType")
                        .HasColumnType("int");

                    b.Property<int>("SpikeHorizonValue")
                        .HasColumnType("int");

                    b.Property<int>("SpikeThresholdAdu")
                        .HasColumnType("int");

                    b.Property<decimal>("SpikeThresholdPercentageRedZone")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SpikeThresholdType")
                        .HasColumnType("int");

                    b.Property<int>("SupplyType")
                        .HasColumnType("int");

                    b.Property<int>("VariabilityCategory")
                        .HasColumnType("int");

                    b.Property<decimal>("VariabilityFactor")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BufferProfiles", (string)null);
                });

            modelBuilder.Entity("Service.Domain.Entities.Calendar", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayOfWeekNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsWorkingDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Date");

                    b.ToTable("Calendar", (string)null);
                });

            modelBuilder.Entity("Service.Domain.Entities.Center", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Zone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Centers", (string)null);
                });

            modelBuilder.Entity("Service.Domain.Entities.CenterProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Adi")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Adu")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("BufferType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Class")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Classification")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("CustomLeadTimeFactor")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(1m);

                    b.Property<decimal>("CustomVariabilityFactor")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(1m);

                    b.Property<decimal?>("Cv")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("FixedBufferProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<int?>("FutureAduDays")
                        .HasColumnType("int");

                    b.Property<decimal?>("GreenZone")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("GreenZoneParametrizationUseAduXFrequency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("GreenZoneParametrizationUseAduXLeadTimeXFactLeadTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("GreenZoneParametrizationUseMoq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("HistoryAduDays")
                        .HasColumnType("int");

                    b.Property<int?>("IdAllocationGroup")
                        .HasColumnType("int");

                    b.Property<int?>("IdBufferProfile")
                        .HasColumnType("int");

                    b.Property<int>("IdCenter")
                        .HasColumnType("int");

                    b.Property<int?>("IdOriginCenter")
                        .HasColumnType("int");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<int?>("IdProvider")
                        .HasColumnType("int");

                    b.Property<int?>("IdReason")
                        .HasColumnType("int");

                    b.Property<int?>("IdTag")
                        .HasColumnType("int");

                    b.Property<int>("LeadTime")
                        .HasColumnType("int");

                    b.Property<decimal>("Moq")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PackQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("QualifiedDemand")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("RedZoneBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("RedZoneSafe")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ReservedStock")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Segment")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SpikeHorizonLTDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("SpikeHorizonType")
                        .HasColumnType("int");

                    b.Property<int>("SpikeHorizonValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(60);

                    b.Property<decimal>("SpikeThresholdAdu")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(1m);

                    b.Property<decimal>("SpikeThresholdPercentageRedZone")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0.5m);

                    b.Property<int>("SpikeThresholdType")
                        .HasColumnType("int");

                    b.Property<decimal?>("StandardDeviation")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Stock")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("UseDafOnGreenZone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("UseSuggestedLTFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("UseSuggestedVariabilityFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("YellowZone")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ZafGreenZone")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ZafRedZone")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ZafYellowZone")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAllocationGroup");

                    b.HasIndex("IdBufferProfile");

                    b.HasIndex("IdCenter");

                    b.HasIndex("IdOriginCenter");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdProvider");

                    b.HasIndex("IdReason");

                    b.HasIndex("IdTag");

                    b.ToTable("CenterProducts", (string)null);
                });

            modelBuilder.Entity("Service.Domain.Entities.DemandAdjustmentFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdjustmentType")
                        .HasColumnType("int");

                    b.Property<decimal>("AdjustmentValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCenter")
                        .HasColumnType("int");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Obs")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCenter");

                    b.HasIndex("IdProduct");

                    b.ToTable("DemandAdjustmentFactors", (string)null);
                });

            modelBuilder.Entity("Service.Domain.Entities.Forecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCenter")
                        .HasColumnType("int");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCenter");

                    b.HasIndex("IdProduct");

                    b.ToTable("Forecasts", (string)null);
                });

            modelBuilder.Entity("Service.Domain.Entities.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Adi")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Adu")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Consumption")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Cv")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiscardStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("Frequency")
                        .HasColumnType("int");

                    b.Property<int?>("FutureAduDays")
                        .HasColumnType("int");

                    b.Property<decimal?>("GreenZone")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("HistoryAduDays")
                        .HasColumnType("int");

                    b.Property<int?>("IdBufferProfile")
                        .HasColumnType("int");

                    b.Property<int>("IdCenter")
                        .HasColumnType("int");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<int?>("IdReason")
                        .HasColumnType("int");

                    b.Property<int?>("IdTag")
                        .HasColumnType("int");

                    b.Property<int?>("LeadTime")
                        .HasColumnType("int");

                    b.Property<decimal?>("Moq")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("OpenInbounds")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("OpenOutbound")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PackQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("QualifiedDemand")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("RedBaseZone")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("RedSafeZone")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ReservedStock")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("StandardDeviation")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Stock")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("YellowZone")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ZafGreenZone")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ZafRedZone")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ZafYellowZone")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdBufferProfile");

                    b.HasIndex("IdCenter");

                    b.HasIndex("IdProduct");

                    b.ToTable("Histories", (string)null);
                });

            modelBuilder.Entity("Service.Domain.Entities.MasterBuffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCenter")
                        .HasColumnType("int");

                    b.Property<int>("IdCenterFather")
                        .HasColumnType("int");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<int>("IdProductFather")
                        .HasColumnType("int");

                    b.Property<int>("Sequency")
                        .HasColumnType("int");

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCenter");

                    b.HasIndex("IdCenterFather");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdProductFather");

                    b.ToTable("MasterBuffers", (string)null);
                });

            modelBuilder.Entity("Service.Domain.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CenterProductId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CenterProductId");

                    b.HasIndex("createdBy");

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("Service.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DeliveredQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdDestinyCenter")
                        .HasColumnType("int");

                    b.Property<int?>("IdOriginCenter")
                        .HasColumnType("int");

                    b.Property<int?>("IdPartner")
                        .HasColumnType("int");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<bool>("IsFictional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsInbound")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOutbound")
                        .HasColumnType("bit");

                    b.Property<string>("MeasurementUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDestinyCenter");

                    b.HasIndex("IdOriginCenter");

                    b.HasIndex("IdPartner");

                    b.HasIndex("IdProduct");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Service.Domain.Entities.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Partners", (string)null);
                });

            modelBuilder.Entity("Service.Domain.Entities.Permission", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Module")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "center:POST",
                            Description = "Create center",
                            Module = "Center"
                        },
                        new
                        {
                            Id = "center:GET",
                            Description = "List centers",
                            Module = "Center"
                        },
                        new
                        {
                            Id = "center:PUT",
                            Description = "Update center",
                            Module = "Center"
                        },
                        new
                        {
                            Id = "center:DELETE",
                            Description = "Delete center",
                            Module = "Center"
                        },
                        new
                        {
                            Id = "role:POST",
                            Description = "Create role",
                            Module = "Role"
                        },
                        new
                        {
                            Id = "role:GET",
                            Description = "List roles",
                            Module = "Role"
                        },
                        new
                        {
                            Id = "role:PUT",
                            Description = "Update role",
                            Module = "Role"
                        },
                        new
                        {
                            Id = "role:DELETE",
                            Description = "Delete role",
                            Module = "Role"
                        },
                        new
                        {
                            Id = "product:POST",
                            Description = "Create product",
                            Module = "Product"
                        },
                        new
                        {
                            Id = "product:GET",
                            Description = "List products",
                            Module = "Product"
                        },
                        new
                        {
                            Id = "product:PUT",
                            Description = "Update product",
                            Module = "Product"
                        },
                        new
                        {
                            Id = "product:DELETE",
                            Description = "Delete product",
                            Module = "Product"
                        },
                        new
                        {
                            Id = "partner:POST",
                            Description = "Create partner",
                            Module = "Partner"
                        },
                        new
                        {
                            Id = "partner:GET",
                            Description = "List partners",
                            Module = "Partner"
                        },
                        new
                        {
                            Id = "partner:PUT",
                            Description = "Update partner",
                            Module = "Partner"
                        },
                        new
                        {
                            Id = "partner:DELETE",
                            Description = "Delete partner",
                            Module = "Partner"
                        },
                        new
                        {
                            Id = "tag:POST",
                            Description = "Create tag",
                            Module = "Tag"
                        },
                        new
                        {
                            Id = "tag:GET",
                            Description = "List tags",
                            Module = "Tag"
                        },
                        new
                        {
                            Id = "tag:PUT",
                            Description = "Update tag",
                            Module = "Tag"
                        },
                        new
                        {
                            Id = "tag:DELETE",
                            Description = "Delete tag",
                            Module = "Tag"
                        },
                        new
                        {
                            Id = "reason:POST",
                            Description = "Create reason",
                            Module = "Reason"
                        },
                        new
                        {
                            Id = "reason:GET",
                            Description = "List reasons",
                            Module = "Reason"
                        },
                        new
                        {
                            Id = "reason:PUT",
                            Description = "Update reason",
                            Module = "Reason"
                        },
                        new
                        {
                            Id = "reason:DELETE",
                            Description = "Delete reason",
                            Module = "Reason"
                        },
                        new
                        {
                            Id = "masterbuffer:POST",
                            Description = "Create master buffer",
                            Module = "MasterBuffer"
                        },
                        new
                        {
                            Id = "masterbuffer:GET",
                            Description = "List master buffers",
                            Module = "MasterBuffer"
                        },
                        new
                        {
                            Id = "masterbuffer:PUT",
                            Description = "Update master buffer",
                            Module = "MasterBuffer"
                        },
                        new
                        {
                            Id = "masterbuffer:DELETE",
                            Description = "Delete master buffer",
                            Module = "MasterBuffer"
                        },
                        new
                        {
                            Id = "bufferprofile:POST",
                            Description = "Create buffer profile",
                            Module = "BufferProfile"
                        },
                        new
                        {
                            Id = "bufferprofile:GET",
                            Description = "List buffer profiles",
                            Module = "BufferProfile"
                        },
                        new
                        {
                            Id = "bufferprofile:PUT",
                            Description = "Update buffer profile",
                            Module = "BufferProfile"
                        },
                        new
                        {
                            Id = "bufferprofile:DELETE",
                            Description = "Delete buffer profile",
                            Module = "BufferProfile"
                        },
                        new
                        {
                            Id = "bufferprofile/active:PATCH",
                            Description = "Set buffer profile active status",
                            Module = "BufferProfile"
                        },
                        new
                        {
                            Id = "allocationgroup:POST",
                            Description = "Create allocation group",
                            Module = "AllocationGroup"
                        },
                        new
                        {
                            Id = "allocationgroup:GET",
                            Description = "List allocation groups",
                            Module = "AllocationGroup"
                        },
                        new
                        {
                            Id = "allocationgroup/priorizedallocation:GET",
                            Description = "View priorized allocation",
                            Module = "AllocationGroup"
                        },
                        new
                        {
                            Id = "allocationgroup/priorizedallocation/run:POST",
                            Description = "Run priorized allocation",
                            Module = "AllocationGroup"
                        },
                        new
                        {
                            Id = "allocationgroup:PUT",
                            Description = "Update allocation group",
                            Module = "AllocationGroup"
                        },
                        new
                        {
                            Id = "allocationgroup:DELETE",
                            Description = "Delete allocation group",
                            Module = "AllocationGroup"
                        },
                        new
                        {
                            Id = "centerproduct:POST",
                            Description = "Create center product",
                            Module = "CenterProduct"
                        },
                        new
                        {
                            Id = "centerproduct:GET",
                            Description = "List center products",
                            Module = "CenterProduct"
                        },
                        new
                        {
                            Id = "centerproduct:PUT",
                            Description = "Update center product",
                            Module = "CenterProduct"
                        },
                        new
                        {
                            Id = "centerproduct:DELETE",
                            Description = "Delete center product",
                            Module = "CenterProduct"
                        },
                        new
                        {
                            Id = "centerproduct/allocation-group:PATCH",
                            Description = "Set center product allocation group",
                            Module = "CenterProduct"
                        },
                        new
                        {
                            Id = "centerproduct/tag:PATCH",
                            Description = "Set center product tag",
                            Module = "CenterProduct"
                        },
                        new
                        {
                            Id = "centerproduct/reason:PATCH",
                            Description = "Set center product reason",
                            Module = "CenterProduct"
                        },
                        new
                        {
                            Id = "bufferadjustmentfactor:POST",
                            Description = "Create buffer adjustment factor",
                            Module = "BufferAdjustmentFactor"
                        },
                        new
                        {
                            Id = "bufferadjustmentfactor:GET",
                            Description = "List buffer adjustment factors",
                            Module = "BufferAdjustmentFactor"
                        },
                        new
                        {
                            Id = "bufferadjustmentfactor:PUT",
                            Description = "Update buffer adjustment factor",
                            Module = "BufferAdjustmentFactor"
                        },
                        new
                        {
                            Id = "bufferadjustmentfactor:DELETE",
                            Description = "Delete buffer adjustment factor",
                            Module = "BufferAdjustmentFactor"
                        },
                        new
                        {
                            Id = "bufferadjustmentfactor/active:PATCH",
                            Description = "Set buffer adjustment factor active status",
                            Module = "BufferAdjustmentFactor"
                        },
                        new
                        {
                            Id = "zoneadjustmentfactor:POST",
                            Description = "Create zone adjustment factor",
                            Module = "ZoneAdjustmentFactor"
                        },
                        new
                        {
                            Id = "zoneadjustmentfactor:GET",
                            Description = "List zone adjustment factors",
                            Module = "ZoneAdjustmentFactor"
                        },
                        new
                        {
                            Id = "zoneadjustmentfactor:PUT",
                            Description = "Update zone adjustment factor",
                            Module = "ZoneAdjustmentFactor"
                        },
                        new
                        {
                            Id = "zoneadjustmentfactor:DELETE",
                            Description = "Delete zone adjustment factor",
                            Module = "ZoneAdjustmentFactor"
                        },
                        new
                        {
                            Id = "zoneadjustmentfactor/active:PATCH",
                            Description = "Set zone adjustment factor active status",
                            Module = "ZoneAdjustmentFactor"
                        },
                        new
                        {
                            Id = "demandadjustmentfactor:POST",
                            Description = "Create demand adjustment factor",
                            Module = "DemandAdjustmentFactor"
                        },
                        new
                        {
                            Id = "demandadjustmentfactor:GET",
                            Description = "List demand adjustment factors",
                            Module = "DemandAdjustmentFactor"
                        },
                        new
                        {
                            Id = "demandadjustmentfactor:PUT",
                            Description = "Update demand adjustment factor",
                            Module = "DemandAdjustmentFactor"
                        },
                        new
                        {
                            Id = "demandadjustmentfactor:DELETE",
                            Description = "Delete demand adjustment factor",
                            Module = "DemandAdjustmentFactor"
                        },
                        new
                        {
                            Id = "demandadjustmentfactor/active:PATCH",
                            Description = "Set demand adjustment factor active status",
                            Module = "DemandAdjustmentFactor"
                        },
                        new
                        {
                            Id = "forecast:POST",
                            Description = "Create forecast",
                            Module = "Forecast"
                        },
                        new
                        {
                            Id = "forecast:GET",
                            Description = "List forecasts (daily breakdown)",
                            Module = "Forecast"
                        },
                        new
                        {
                            Id = "forecast/grouped:GET",
                            Description = "List forecasts (grouped by period)",
                            Module = "Forecast"
                        },
                        new
                        {
                            Id = "forecast:PUT",
                            Description = "Update forecast",
                            Module = "Forecast"
                        },
                        new
                        {
                            Id = "forecast:DELETE",
                            Description = "Delete forecast",
                            Module = "Forecast"
                        },
                        new
                        {
                            Id = "history:POST",
                            Description = "Create history record",
                            Module = "History"
                        },
                        new
                        {
                            Id = "history:GET",
                            Description = "List history records",
                            Module = "History"
                        },
                        new
                        {
                            Id = "history:PUT",
                            Description = "Update history record",
                            Module = "History"
                        },
                        new
                        {
                            Id = "history:DELETE",
                            Description = "Delete history record",
                            Module = "History"
                        },
                        new
                        {
                            Id = "history/discard-status:PATCH",
                            Description = "Set history discard status",
                            Module = "History"
                        },
                        new
                        {
                            Id = "note:POST",
                            Description = "Create note",
                            Module = "Note"
                        },
                        new
                        {
                            Id = "note:GET",
                            Description = "List notes",
                            Module = "Note"
                        },
                        new
                        {
                            Id = "note:PUT",
                            Description = "Update note",
                            Module = "Note"
                        },
                        new
                        {
                            Id = "note:DELETE",
                            Description = "Delete note",
                            Module = "Note"
                        },
                        new
                        {
                            Id = "order:POST",
                            Description = "Create order",
                            Module = "Order"
                        },
                        new
                        {
                            Id = "order:GET",
                            Description = "List orders",
                            Module = "Order"
                        },
                        new
                        {
                            Id = "order:PUT",
                            Description = "Update order",
                            Module = "Order"
                        },
                        new
                        {
                            Id = "order:DELETE",
                            Description = "Delete order",
                            Module = "Order"
                        },
                        new
                        {
                            Id = "user:POST",
                            Description = "Create user",
                            Module = "User"
                        },
                        new
                        {
                            Id = "user:GET",
                            Description = "List users",
                            Module = "User"
                        },
                        new
                        {
                            Id = "user:PUT",
                            Description = "Update user",
                            Module = "User"
                        },
                        new
                        {
                            Id = "user:DELETE",
                            Description = "Delete user",
                            Module = "User"
                        },
                        new
                        {
                            Id = "workspace:PUT",
                            Description = "Update workspace",
                            Module = "Workspace"
                        },
                        new
                        {
                            Id = "workspace:DELETE",
                            Description = "Clear workspace",
                            Module = "Workspace"
                        },
                        new
                        {
                            Id = "ai/ask:POST",
                            Description = "Ask AI assistant",
                            Module = "Ai"
                        },
                        new
                        {
                            Id = "ai/chat:GET",
                            Description = "View AI chat history",
                            Module = "Ai"
                        },
                        new
                        {
                            Id = "ingestion/run:POST",
                            Description = "Run ingestion pipeline",
                            Module = "Ingestion"
                        },
                        new
                        {
                            Id = "calculation/run:POST",
                            Description = "Run calculation pipeline",
                            Module = "Calculation"
                        },
                        new
                        {
                            Id = "robot/run:POST",
                            Description = "Run robot (ingestion + calculation)",
                            Module = "Robot"
                        },
                        new
                        {
                            Id = "report/inventorybuffermanagement:GET",
                            Description = "View inventory buffer management report",
                            Module = "Report"
                        },
                        new
                        {
                            Id = "report/inventorybuffermanagement/colorsummary:GET",
                            Description = "View inventory buffer management color summary",
                            Module = "Report"
                        },
                        new
                        {
                            Id = "report/openorders/inbounds:GET",
                            Description = "View open orders report",
                            Module = "Report"
                        },
                        new
                        {
                            Id = "report/inventoryhistory:GET",
                            Description = "View inventory history report",
                            Module = "Report"
                        },
                        new
                        {
                            Id = "report/projectedstockalert:GET",
                            Description = "View projected stock alert report",
                            Module = "Report"
                        },
                        new
                        {
                            Id = "report/bufferpenetration:GET",
                            Description = "View buffer penetration report",
                            Module = "Report"
                        },
                        new
                        {
                            Id = "report/itemsbybuffercolorhistory:GET",
                            Description = "View items by buffer color history report",
                            Module = "Report"
                        },
                        new
                        {
                            Id = "report/accumulatedbufferhistory:GET",
                            Description = "View accumulated buffer history report",
                            Module = "Report"
                        });
                });

            modelBuilder.Entity("Service.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuxiliarMaterialCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Line")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Pallet")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Segment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Subline")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Volume")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("WorkCenter")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Service.Domain.Entities.Reason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsFromSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reasons", (string)null);
                });

            modelBuilder.Entity("Service.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Service.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Service.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<string>("IdPermission")
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("IdRole", "IdPermission");

                    b.HasIndex("IdPermission");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("Service.Domain.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("FridayIsWorkingDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("MondayIsWorkingDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("SaturdayIsWorkingDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("SundayIsWorkingDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("ThursdayIsWorkingDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("TuesdayIsWorkingDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("WednesdayIsWorkingDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FridayIsWorkingDay = true,
                            MondayIsWorkingDay = true,
                            SaturdayIsWorkingDay = false,
                            SundayIsWorkingDay = false,
                            ThursdayIsWorkingDay = true,
                            TuesdayIsWorkingDay = true,
                            WednesdayIsWorkingDay = true
                        });
                });

            modelBuilder.Entity("Service.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("Service.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ThreadId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdRole");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Service.Domain.Entities.Workspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<int>("IdCenter")
                        .HasColumnType("int");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<decimal>("OptimizedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCenter");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdUser");

                    b.ToTable("Workspaces", (string)null);
                });

            modelBuilder.Entity("Service.Domain.Entities.ZoneAdjustmentFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdjustmentType")
                        .HasColumnType("int");

                    b.Property<decimal>("AdjustmentValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCenter")
                        .HasColumnType("int");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Obs")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TargetZone")
                        .HasColumnType("int");

                    b.Property<DateTime?>("createdAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCenter");

                    b.HasIndex("IdProduct");

                    b.ToTable("ZoneAdjustmentFactors", (string)null);
                });

            modelBuilder.Entity("Service.Domain.Entities.BufferAdjustmentFactor", b =>
                {
                    b.HasOne("Service.Domain.Entities.Center", "Center")
                        .WithMany()
                        .HasForeignKey("IdCenter")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Service.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Center");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Service.Domain.Entities.CenterProduct", b =>
                {
                    b.HasOne("Service.Domain.Entities.AllocationGroup", "AllocationGroup")
                        .WithMany()
                        .HasForeignKey("IdAllocationGroup")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Service.Domain.Entities.BufferProfile", "BufferProfile")
                        .WithMany()
                        .HasForeignKey("IdBufferProfile")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Service.Domain.Entities.Center", "Center")
                        .WithMany()
                        .HasForeignKey("IdCenter")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Service.Domain.Entities.Center", "OriginCenter")
                        .WithMany()
                        .HasForeignKey("IdOriginCenter")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Service.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Service.Domain.Entities.Partner", "Provider")
                        .WithMany()
                        .HasForeignKey("IdProvider")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Service.Domain.Entities.Reason", "Reason")
                        .WithMany()
                        .HasForeignKey("IdReason")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Service.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("IdTag")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AllocationGroup");

                    b.Navigation("BufferProfile");

                    b.Navigation("Center");

                    b.Navigation("OriginCenter");

                    b.Navigation("Product");

                    b.Navigation("Provider");

                    b.Navigation("Reason");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Service.Domain.Entities.DemandAdjustmentFactor", b =>
                {
                    b.HasOne("Service.Domain.Entities.Center", "Center")
                        .WithMany()
                        .HasForeignKey("IdCenter")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Service.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Center");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Service.Domain.Entities.Forecast", b =>
                {
                    b.HasOne("Service.Domain.Entities.Center", "Center")
                        .WithMany()
                        .HasForeignKey("IdCenter")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Service.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Center");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Service.Domain.Entities.History", b =>
                {
                    b.HasOne("Service.Domain.Entities.BufferProfile", "BufferProfile")
                        .WithMany()
                        .HasForeignKey("IdBufferProfile")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Service.Domain.Entities.Center", "Center")
                        .WithMany()
                        .HasForeignKey("IdCenter")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Service.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BufferProfile");

                    b.Navigation("Center");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Service.Domain.Entities.MasterBuffer", b =>
                {
                    b.HasOne("Service.Domain.Entities.Center", "Center")
                        .WithMany()
                        .HasForeignKey("IdCenter")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Service.Domain.Entities.Center", "CenterFather")
                        .WithMany()
                        .HasForeignKey("IdCenterFather")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Service.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Service.Domain.Entities.Product", "ProductFather")
                        .WithMany()
                        .HasForeignKey("IdProductFather")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Center");

                    b.Navigation("CenterFather");

                    b.Navigation("Product");

                    b.Navigation("ProductFather");
                });

            modelBuilder.Entity("Service.Domain.Entities.Note", b =>
                {
                    b.HasOne("Service.Domain.Entities.CenterProduct", "CenterProduct")
                        .WithMany()
                        .HasForeignKey("CenterProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Service.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("createdBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CenterProduct");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Service.Domain.Entities.Order", b =>
                {
                    b.HasOne("Service.Domain.Entities.Center", "DestinyCenter")
                        .WithMany()
                        .HasForeignKey("IdDestinyCenter")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Service.Domain.Entities.Center", "OriginCenter")
                        .WithMany()
                        .HasForeignKey("IdOriginCenter")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Service.Domain.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("IdPartner")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Service.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinyCenter");

                    b.Navigation("OriginCenter");

                    b.Navigation("Partner");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Service.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Service.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Service.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Service.Domain.Entities.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("IdPermission")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Service.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Service.Domain.Entities.User", b =>
                {
                    b.HasOne("Service.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Service.Domain.Entities.Workspace", b =>
                {
                    b.HasOne("Service.Domain.Entities.Center", "Center")
                        .WithMany()
                        .HasForeignKey("IdCenter")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Service.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Service.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Center");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Service.Domain.Entities.ZoneAdjustmentFactor", b =>
                {
                    b.HasOne("Service.Domain.Entities.Center", "Center")
                        .WithMany()
                        .HasForeignKey("IdCenter")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Service.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Center");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Service.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
