<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Service.Application\Service.Application.csproj" />
    <ProjectReference Include="..\Service.Domain\Service.Domain.csproj" />
    <ProjectReference Include="..\Service.Infra.Data\Service.Infra.Data.csproj" />
  </ItemGroup>

</Project>
